### ISSUE TITLE
wrong result when using std::view::zip

### ISSUE THREAD

**Issue by yuanzihao-1991** [timsort/cpp-TimSort#40] opened 2024-11-28 12:48 UTC
Here is my code compiled with option -std=c++23, gcc 14.2:
```c++
#include "timsort.hpp"
#include <array>
#include <iostream>
#include <tuple>
#include <vector>

int main() {
  auto x = std::vector{4, 2, 3, 1};
  auto y = std::array{'A', 'C', 'B', 'D'};
  auto xy = std::views::zip(x, y);

  gfx::timsort(xy, {},
   [](const std::tuple<int &, char &> &a) {
    return std::get<0>(a);
  });

  for (std::tuple<int &, char &> elem : xy) {
    std::cout << std::get<0>(elem) << ' ' << std::get<1>(elem) << ' ' << '\n';
  }
}
```
Expected result is:
```
1 D 
2 C 
3 B 
4 A
```
However, I got
```
4 A 
2 C 
4 A 
4 A 
```

**Comment by Morwenn** [comment] 2024-11-28 18:56
Hi, and thanks for the bug report!

I confirm the issue, and it looks like a bug since `std::ranges::sort` works very well there. I am going to investigate the issue.

**Comment by Morwenn** [comment] 2024-11-28 22:32
It turns out that I did not handle proxy iterators correctly. I pushed a new commit to branch `3.x.y` which fixes the issue.

The pipeline is partly broken because the CI jobs were meant to target C++20 and I will have some additional work to do in that area, but I ran tests locally with GCC 14, and the issues seems fixed.

**Comment by yuanzihao-1991** [comment] 2024-11-29 01:41
> It turns out that I did not handle proxy iterators correctly. I pushed a new commit to branch `3.x.y` which fixes the issue.
> 
> The pipeline is partly broken because the CI jobs were meant to target C++20 and I will have some additional work to do in that area, but I ran tests locally with GCC 14, and the issues seems fixed.

Great! Thanks a lot for your quick response and efforts!

**Comment by Morwenn** [comment] 2024-12-01 17:56
No problem!

Do you confirm that the issue is fixed on your side? If so, we can close that ticket.

**Comment by yuanzihao-1991** [comment] 2024-12-02 03:56
> No problem!
> 
> Do you confirm that the issue is fixed on your side? If so, we can close that ticket.

Confirmed. Perfect! Thank you!

**Closed as completed** 2024-12-02 09:15 UTC
Labels: bug
